[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ffxi-resources"
version = "1.0.0"
requires-python = ">=3.11"

dependencies = [
    "construct>=2.10",
    "loguru>=0.7",
    "pillow>=10.0",
    "pyarrow>=15.0",
    "xi-events @ git+https://github.com/sruon/xi-events-py.git",
    "pydantic>=2.0",
    "pyyaml>=6.0",
]

[tool.setuptools]
packages = ["parsers", "models", "writers"]

[tool.black]
line-length = 160
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 160
