name: Release Notification

on:
  release:
    types:
      - published

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/release-notifier-action@v2
        with:
          app_id: ${{ secrets.NOTIFIER_APP_ID }}
          private_key: ${{ secrets.NOTIFIER_APP_PRIVATE_KEY }}
